### ISSUE TITLE
Batch job stuck in RUNNABLE state (AMI cannot be described)

### ISSUE THREAD

**Issue by usuyama** [aws-quickstart/quickstart-illumina-dragen#35]
I'm following the quick start guide https://aws-quickstart.s3.amazonaws.com/quickstart-illumina-dragen/doc/dragen-on-the-aws-cloud.pdf

I submitted a sample job but it's stuck in the RUNNABLE state forever

It seems the issue is Compute environments are in INVALID states (both ondemand and spot)
![image](https://user-images.githubusercontent.com/344133/103440194-f2eed880-4c86-11eb-8c5e-8f1c6384d2b3.png)

the error is `INVALID - CLIENT_ERROR - AMI cannot be described`
![image](https://user-images.githubusercontent.com/344133/103440282-701a4d80-4c87-11eb-9b9b-6b8c10a9d9b1.png)

I just double-checked the deployment status, but all steps completed without errors:
![image](https://user-images.githubusercontent.com/344133/103440258-50832500-4c87-11eb-8e86-59e48321d8ce.png)

Any idea why the AMI is not found?

**Comment by usuyama** [comment]
any thoughts? @partha-edico @vsnyc

**Comment by ajfriedman18** [comment]
@usuyama what happens if you spin up a separate EC2 instance with the same AMI ID? My guess is that the AMI is the one from AWS Marketplace and you haven't procured it

**Comment by usuyama** [comment]
Thanks for your comment, @ajfriedman18 

I already have access to "DRAGEN Complete Suite" on AWS Marketplace. Do I need to subscribe to other resources?

![image](https://user-images.githubusercontent.com/344133/103604925-befd0700-4f55-11eb-9a3b-3258f337f3d0.png)

**Comment by ajfriedman18** [comment]
Got it - are you able to launch a new instance in us-west-2 with it?

**Comment by vsnyc** [comment]
@usuyama - Sorry for the delay, this happened because the quick start was using an older version of the AMI that passes in our tests but is no longer available to new customers. While testing the AMI update, we ran into another issue, where jobs would get stuck in a RUNNABLE state due to a timing issue with respect to running the ecs agent and it picking up the updated configuration. To work around the fact, I am now passing in a LaunchTemplate that contains user data to retry and restart the ecs-agent. This fix is in this PR: https://github.com/aws-quickstart/quickstart-illumina-dragen/pull/36, I'll keep you posted when this is validated, tested and merged with main branch.

**Comment by usuyama** [comment]
Great to hear that you found the root cause. Looking forward to trying the
quick start again once it's fixed.

**Comment by vsnyc** [comment]
@usuyama - I missed to notify but the quick start no longer has the issues you were running into earlier. We've also updated the AMI version used by the quick start. Please retry and open a new issue if you run into anything. 

Best regards, 
Vinod
